### ISSUE TITLE
갤러리에 낙관폴더가 뜨던데 .nomedia 적용하면 앱 구동에 문제가 발생할까요?

### ISSUE THREAD

**Issue by HYNIX-Jang** [5seunghoon/PreviewMaker#4]
가끔 갤러리 정리하다가 모르고 낙관 폴더 바보같이 삭제해버려서 갤러리에 안뜨는게 사용자입장에서 좋다고 생각하는데  .nomedia 적용을 업데이트에 적용하면 어떨까요?

**Comment by 5seunghoon** [comment]
한동한 신경못쓰고 살았는데 이슈를 달아주셨네요. 관심 감사합니다.
좋은 아이디어인거 같습니다! 차후 적용해보겠습니다. 감사해요!

**Comment by HYNIX-Jang** [comment]
우왕 리플라이 달아주시다니ㅠㅠ 너무 잘 사용하고 있습니다ㅎㅎ

**Comment by 5seunghoon** [comment]
아닙니다.. 늦은 리플라이가 죄송할 다름.. 
잘 사용하고 계신다니 영광입니다.. 
칼핀 기원드리겠습니다 ㅋㅋㅋㅋ

**Comment by 5seunghoon** [comment]
Merge : https://github.com/5seunghoon/PreviewMaker/pull/20
